### ISSUE TITLE
Plugin seems to be called before CF variables are evaluated

### ISSUE THREAD

**Issue by henhal** [chechu/serverless-dynamodb-fixtures#11]
# This is a Bug Report

## Description

For bug reports:

It's not possible to use `!Ref` or `!GetAtt` expressions in the `custom.fixtures` section.
Example:

```
  fixtures:
    rules:
      - table: '${{self:provider.stage}}-foobar' # !Ref FoobarTable doesn't work
        enable: true
        sources:
          - ./fixtures/foobars.json

```

Using `!Ref` renders a mysterious error message about keys not being according to format:

`... at 'requestItems' failed to satisfy constraint: Map keys must satisfy constraint: [Member must have length less than or equal to 255, Member must have length greater than or equal to 3, Member must satisfy regular expression pattern: [a-zA-Z0-9_.-]+]`

It took me a while to realize that this was due to the `!Ref`; the literal value `!Ref: FoobarTable` was apparently used instead of the table name resolved through the CF function.

Similar or dependent issues:

N/A

## Additional Data

* ***Operating System***: Ubuntu
* ***Stack Trace***:
* ***Provider Error messages***: 

```
Serverless: Invoke fixtures
Serverless: Loading fixtures for table [object Object]
 
  Validation Exception -----------------------------------
 
  ValidationException: 1 validation error detected: Value '{[object Object]=[WriteRequest(putRequest=PutRequest(item={name=AttributeValue <snip> }), deleteRequest=null)]}' at 'requestItems' failed to satisfy constraint: Map keys must satisfy constraint: [Member must have length less than or equal to 255, Member must have length greater than or equal to 3, Member must satisfy regular expression pattern: [a-zA-Z0-9_.-]+]
      at Request.extractError
```

(retracted)
